server:
  port: 8080
spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HyperionOJ
        namespace: beec702e-19ab-441b-840c-e0f67a42b0f5
        ephemeral: true
    gateway:
      routes:
        - id: ping-consumer-service
          uri: lb://consumer
          predicates:
            - Path=/ping/**
            #- After=
            #- Befor=
            #- Cookie=
            #filters:
            #- AddRequestHeader

        - id: oss-service
          uri: lb://oss
          predicates:
            - Path=/login, /register

        - id: finduser-service
          uri: lb://consumer
          predicates:
            - Path=/findUserById/*
          filters:
            - RewritePath=/findUserById/(?<segment>.*),/ping/userId/$\{segment}
      default-filters:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "https://localhost:9000"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000
