server:
  port: 9999
spring:
  application:
    name: admin
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HyperionOJ
        ephemeral: true
        namespace: 0e00e406-05ce-4cc8-a5d0-e5038753b730
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hyperionoj?serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123212321
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    #允许存在多个Feign调用相同Service的接口
    allow-bean-definition-overriding: true
mybatis-plus:
  mapper-locations: classpath:com/hyperionoj/dao/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: oj_
feign:
  client:
    config:
      default:
        loggerLevel: full
        requestInterceptors:
          - com.hyperionoj.common.interceptor.DefaultFeignConfiguration