server:
  port: 9900
spring:
  application:
    name: judge
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HyperionOJ
        ephemeral: true
        namespace: 0e00e406-05ce-4cc8-a5d0-e5038753b730
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      # 发生错误后，消息重发的次数。
      retries: 3
      # 键的序列化方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 值的序列化方式
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: judgeTest
      # 键的反序列化方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 值的反序列化方式
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.artisan.springkafka.domain
    listener:
      # 但消费者监听的topic不存在时，保证能够是项目启动
      missing-topics-fatal: false
judge:
  fileDir:
    problem: D:\WorkSpace\Java_Works\IDEA_Works\HyperionOJ\judge\problem_data
    submit: D:\WorkSpace\Java_Works\IDEA_Works\HyperionOJ\judge\submit_data
