server:
  port: 9000
spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HyperionOJ
        namespace: 8c23f025-5aae-49be-8505-eb6ddce4970a
        ephemeral: true
    gateway:
      routes:
        - id: oss-service
          uri: lb://oss
          predicates:
            - Path=/ping, /login/*, /register/*, /vercode/*, /destroy, /update/*, /vercode
            #- After=
            #- Befor=
            #- Cookie=
            #filters:
            #- AddRequestHeader
        - id: page-service
          uri: lb://page
          predicates:
            - Path=/test/*
        - id: finduser-service
          uri: lb://consumer
          predicates:
            - Path=/findUserById/*
          filters:
            - RewritePath=/findUserById/(?<segment>.*),/ping/userId/$\{segment}
      default-filters:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "https://localhost:9000"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000
