server:
  port: 9000
spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HyperionOJ
        namespace: 8c23f025-5aae-49be-8505-eb6ddce4970a
        ephemeral: true
    gateway:
      routes:
        - id: oss-service
          uri: lb://oss
          predicates:
            - Path=/ping, /login/*, /register/*, /vercode/*, /destroy, /update/*, /vercode,/find/**
            #- After=
            #- Befor=
            #- Cookie=
            #filters:
            #- AddRequestHeader
        - id: judge-service
          uri: lb://judge
          predicates:
            - Path=/submit
        - id: page-service
          uri: lb://page
          predicates:
            - Path=/problem/**, /article/**, /contests/**,/school/**,/contest/**
        - id: admin-service
          uri: lb://admin
          predicates:
            - Path=/admin/**
        - id: common-server
          uri: lb://common
          predicates:
            - Path=/upload/**
      default-filters:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowCredentials: true
            allowedOrigins:
              - "http://localhost:8080"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            maxAge: 360000